<?php
require_once '../../../backend/config/functions.php';
requireRole('principal');
?><!DOCTYPE html>
<html lang="en">
<head>
  <script>
    (function(){
      var t = localStorage.getItem('ueples_theme') || 'dark';
      document.documentElement.dataset.theme = t;
      window.addEventListener('DOMContentLoaded', function() {
        var btn = document.getElementById('themeBtn');
        if(btn) btn.textContent = t === 'dark' ? '🌙' : '☀️';
      });
    })();
    function toggleTheme() {
      var next = document.documentElement.dataset.theme === 'dark' ? 'light' : 'dark';
      document.documentElement.dataset.theme = next;
      localStorage.setItem('ueples_theme', next);
      var btn = document.getElementById('themeBtn');
      if(btn) btn.textContent = next === 'dark' ? '🌙' : '☀️';
    }
  </script>
  <meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
  <title>Rooms — Principal</title>
  <link rel="stylesheet" href="../../assets/css/style.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css">
  <style>
    :root{--accent:#8b5cf6;--accent-bg:rgba(139,92,246,.12)} /* Violet */
    .room-grid{display:grid;grid-template-columns:repeat(auto-fill, minmax(300px, 1fr));gap:20px;padding:20px}
    .room-card{background:var(--bg-card);border:1px solid var(--border);border-radius:var(--radius-md);overflow:hidden;}
    .room-header{background:rgba(255,255,255,.03);padding:16px;border-bottom:1px solid var(--border);display:flex;justify-content:space-between;align-items:center}
    .room-title{font-weight:700;font-size:1.1rem;color:var(--text);display:flex;align-items:center;gap:8px}
    .room-body{padding:16px;font-size:.9rem;color:var(--text-sub)}
    .room-stats{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-top:10px}
    .room-stat{background:var(--bg-ele);border:1px solid var(--border);border-radius:8px;padding:8px;text-align:center}
    .room-stat strong{display:block;font-size:1rem;color:var(--text)}
    .mini-grid{display:grid;grid-template-columns:100px repeat(6,1fr);border:1px solid var(--border);border-radius:8px;overflow:hidden}
    .mini-h{background:var(--bg-ele);padding:6px;font-size:.72rem;font-weight:700;text-align:center;border-right:1px solid var(--border);border-bottom:1px solid var(--border)}
    .mini-time{padding:6px;font-size:.7rem;color:var(--text-muted);border-right:1px solid var(--border);border-bottom:1px solid var(--border)}
    .mini-cell{height:26px;border-right:1px solid rgba(128,128,128,.2);border-bottom:1px solid rgba(128,128,128,.2);background:var(--cell-free)}
    .mini-cell.busy{background:var(--cell-teacher)}
    .mini-cell.free{background:rgba(16,185,129,.08)}
  </style>
</head>
<body class="page-body">

<header class="main-header">
  <div class="brand"><i class="fa-solid fa-school"></i><span>PRINCIPAL PORTAL</span></div>
  <nav class="top-nav">
    <a href="../dashboard/index.php"><i class="fa-solid fa-gauge-high"></i> Dashboard</a>
    <a href="../students/index.php"><i class="fa-solid fa-user-graduate"></i> Students</a>
    <a href="../teachers/index.php"><i class="fa-solid fa-chalkboard-user"></i> Teachers</a>
    <a href="index.php" class="active"><i class="fa-solid fa-door-open"></i> Rooms</a>
    <a href="../profile/index.php"><i class="fa-solid fa-user-circle"></i> Profile</a>
    <a href="../../../backend/auth/logout.php" class="btn-logout"><i class="fa-solid fa-right-from-bracket"></i> Logout</a>
      <button class="theme-btn" id="themeBtn" title="Toggle theme" onclick="toggleTheme()">🌙</button>
  </nav>
</header>

<main class="page-content" style="max-width:1400px">
  <div class="page-header">
    <div class="page-header-text"><h2><i class="fa-solid fa-map" style="color:var(--accent)"></i> Campus Rooms</h2><p>Overview of classroom utilization and capacities.</p></div>
  </div>

  <div class="section-card">
    <div class="toolbar" style="display:flex;gap:12px;padding:16px;border-bottom:1px solid var(--border)">
       <select class="filter-sel" id="fBldg" onchange="loadRooms()"><option value="">All Buildings</option></select>
    </div>
    
    <div id="loadingWrap" style="text-align:center;padding:40px;color:var(--text-muted)">
        <i class="fa-solid fa-spinner fa-spin" style="font-size:2rem;margin-bottom:12px"></i>
        <p>Loading rooms...</p>
    </div>

    <div class="room-grid" id="roomWrap" style="display:none">
      <!-- Generated by JS -->
    </div>
    
  </div>
</main>

<div class="modal-overlay" id="roomDetailModal">
  <div class="modal modal-lg">
    <div class="modal-header">
      <h3 id="roomDetailTitle"><i class="fa-solid fa-door-open"></i> Room Details</h3>
      <button class="modal-close" onclick="closeRoomDetail()"><i class="fa-solid fa-xmark"></i></button>
    </div>
    <div class="modal-body">
      <div id="roomDetailStats" class="room-stats"></div>
      <h4 style="margin:14px 0 8px">Weekly Occupancy</h4>
      <div id="roomMiniGrid"></div>
      <h4 style="margin:14px 0 8px">Scheduled Classes</h4>
      <div class="table-wrap">
        <table class="data-table">
          <thead><tr><th>Type</th><th>Subject</th><th>Teacher</th><th>Grade/Section</th><th>Day</th><th>Time</th></tr></thead>
          <tbody id="roomScheduleBody"></tbody>
        </table>
      </div>
      <h4 style="margin:14px 0 8px">Available Time Blocks</h4>
      <div id="roomAvailable"></div>
    </div>
  </div>
</div>
<script src="script.js"></script>
</body></html>
